---
- name: Setup Owner
  file: path={{ apache_root }} owner=vagrant group=users recurse=true
  sudo: yes

- name: checkout repo
  tags:
   - shopware
  git:
    repo={{ shopware_repo_url }}
    dest={{ shopware_install_path }}
    force=false
    update=false

- name: Copy configuration
  tags:
  template:
    src=build.properties.j2
    dest={{ shopware_install_path }}/build/build.properties
    owner=vagrant
    group=users
  sudo: yes

- name: Copy create cache script
  tags:
  template:
    src=make_cache_dirs.j2
    dest=/etc/init.d/make_cache_dirs
    owner=root
    group=root
    mode=0755
  sudo: yes

- name: Autstart cache script
  service: name=make_cache_dirs enabled=yes
  sudo: yes

- name: Run cache script initially
  command: /etc/init.d/make_cache_dirs
    creates=/dev/shm/cache/doctrine/attributes/
  sudo: yes

- name: Setup Owner for cache dir
  file: path=/dev/shm/cache/ mode=777 owner={{ apache_user }} group={{ apache_user }} recurse=true
  sudo: yes

- name: Run Ant
  command: ant -f {{ shopware_install_path }}/build/build.xml build-config build-composer-install build-database build-snippets-deploy
    creates={{ shopware_install_path }}/engine/Shopware/Configs/Custom.php

- name: Download demodata
  get_url:
    url={{ shopware_demo_data_url }}
    dest={{ apache_root }}/demo.zip
    force=no

- name: Unzip demodata
  command: unzip -u -q {{ apache_root }}/demo.zip -d {{ shopware_install_path }}/

- name: Setup Permissions
  file: path={{ item }} recurse=true state=directory mode=777
  with_items:
    - "{{ shopware_install_path }}/cache"
    - "{{ shopware_install_path }}/logs"
